spring:
  datasource:
    password: '!Password1'
    url: jdbc:mysql://localhost:3306/calories_calculator
    username: root
  liquibase:
    change-log: liquibase/db.changelog-master.yml
    url: jdbc:mysql://localhost:3306/calories_calculator
    user: root
    password: '!Password1'
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
        format_sql: true
      show-sql: true
      open-in-view: false